### ISSUE TITLE
cannot activate 5g on D-link daw-182 rev D.1 chipset: RTL8812BU

### ISSUE THREAD

**Issue by sollted** [ivanovborislav/rtl8821au#2]
This driver was only one that worked for me but I still can activate 5g on my ubuntu

I made file 88x2bu.conf in /etc/modprobe.d
the led control is set to 2 in order to test if the file has any effect on the wifi adapter 

**in this file is:**

```
options 88x2bu
rtw_ips_mode=1
rtw_drv_log_level=4
rtw_power_mgnt=2
rtw_led_ctrl=2
rtw_wireless_mode=16
```

I tried without the first line because I am not sure about it : `options 88x2bu`
**second try with 88x2bu.conf in /etc/modprobe.d:**

```
rtw_ips_mode=1
rtw_drv_log_level=4
rtw_power_mgnt=2
rtw_led_ctrl=2
rtw_wireless_mode=16
```

**my ubuntu version (uname -a):**

`Linux a-MacBookPro 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**output of iwconfig:**
```
lo        no wireless extensions.

enp2s0f0  no wireless extensions.

wlp3s0    IEEE 802.11  ESSID:"XXX"
          Mode:Managed  Frequency:5.24 GHz  Access Point: XX:XX:XX:XX:XX:XX
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

wlxa0a3f0ca408e  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=**2.412 GHz**  Access Point: Not-Associated
          Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

I tried other rtw_wireless_modes but every time it was set to 2.412 GHz

any help is much appreciated

**Comment by ivanovborislav** [comment]
Hi!
Try to connect to 5GHz WiFi network.

**Comment by sollted** [comment]
Thanks for quick response.
after connecting to 5GHz network It is working correctly. 
I am new to all of this and probably wouldn't find this problem.

**Comment by ivanovborislav** [comment]
I am happy to help!
